### ISSUE TITLE
出现了一个bug

### ISSUE THREAD

**Issue by demon1q** [mustfun/mybatis-plus#21]
![image](https://user-images.githubusercontent.com/43901891/54067402-7fdacd80-427a-11e9-8862-f95d8b167757.png)
```java
java.lang.IllegalStateException: Optional.get() cannot be called on an absent value
	at com.google.common.base.Absent.get(Absent.java:43)
	at com.github.mustfun.mybatis.plugin.contributor.TestParamContributor.addElementForPsiParameter(TestParamContributor.java:43)
	at com.github.mustfun.mybatis.plugin.contributor.SqlParamCompletionContributor.process(SqlParamCompletionContributor.java:49)
	at com.github.mustfun.mybatis.plugin.contributor.SqlParamCompletionContributor.fillCompletionVariants(SqlParamCompletionContributor.java:37)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:87)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:149)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:142)
	at com.intellij.codeInsight.template.impl.LiveTemplateCompletionContributor$2.addCompletions(LiveTemplateCompletionContributor.java:96)
	at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:36)
	at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:141)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:87)
	at com.intellij.codeInsight.completion.impl.CompletionServiceImpl.performCompletion(CompletionServiceImpl.java:63)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.calculateItems(CompletionProgressIndicator.java:827)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.runContributors(CompletionProgressIndicator.java:812)
	at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.lambda$null$2(CodeCompletionHandlerBase.java:272)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1168)
	at com.intellij.codeInsight.completion.AsyncCompletion.tryReadOrCancel(CompletionThreading.java:169)
	at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.lambda$doComplete$3(CodeCompletionHandlerBase.java:269)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$null$0(CompletionThreading.java:95)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:582)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:87)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$startThread$1(CompletionThreading.java:91)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by mustfun** [comment]
谢谢反馈

**Comment by cmgdmxw** [comment]
请问你的日志是在哪看的，我目前碰到点击生成文件但是无文件产生，无报错

**Comment by mustfun** [comment]
> 请问你的日志是在哪看的，我目前碰到点击生成文件但是无文件产生，无报错

 右下角会出现一个感叹号，一直在闪烁，点击出现详情，上面这个错误不影响生成文件

**Comment by cmgdmxw** [comment]
好吧，谢谢你了！我没有任何感叹号什么的，波澜不惊。没有任何变化，感觉点了个假按钮
------------------ 原始邮件 ------------------
发件人: "mustfun"<notifications@github.com>;
发送时间: 2019年5月28日(星期二) 中午11:11
收件人: "mustfun/mybatis-plus"<mybatis-plus@noreply.github.com>;
抄送: "淘宝网"<1163028612@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [mustfun/mybatis-plus] 出现了一个bug (#21)



 
请问你的日志是在哪看的，我目前碰到点击生成文件但是无文件产生，无报错
  
右下角会出现一个感叹号，一直在闪烁，点击出现详情，上面这个错误不影响生成文件

**Comment by mustfun** [comment]
@cmgdmxw  不是假按钮，建议更换2018.2以上版本的idea，配合最新版插件使用，数据库在5.6以上，效果应该就有了

**Comment by cmgdmxw** [comment]
下载了一个新版本的2019.1的idea 先后生成两张表回产生文件错乱~~




------------------ 原始邮件 ------------------
发件人: "mustfun"<notifications@github.com>;
发送时间: 2019年5月28日(星期二) 中午11:17
收件人: "mustfun/mybatis-plus"<mybatis-plus@noreply.github.com>;
抄送: "淘宝网"<1163028612@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [mustfun/mybatis-plus] 出现了一个bug (#21)




@cmgdmxw  不是假按钮，建议更换2018.2以上版本的idea，配合最新版插件使用，数据库在5.6以上，效果应该就有了
